import type { AdventurerDefinition } from '@expedition/shared-types';

export const GUILD_ADVENTURERS: readonly AdventurerDefinition[] = [
  {
    id: 'brann',
    name: '布蘭',
    title: '不動鐵壁',
    role: 'vanguard',
    baseStats: { hp: 10, attack: 1, defense: 1, speed: 1, healing: 1 },
    skillIds: ['basic_attack', 'shield_wall'],
    starterSkillIds: [
      'fire.stack.battle_open',
      'fire.weaken.target_burning',
      'water.empower.previous_fire',
      'fire.multistrike.on_repeat_hit',
      'grass.chain.target_burning',
      'fire.blast.consume_burn',
    ],
    deliveryPassive: {
      id: 'ironwall-delivery',
      name: '盾火開路',
      description: '布蘭打出本回合第一招時，額外建立一層燃燒與削弱。',
    },
  },
  {
    id: 'lyra',
    name: '萊拉',
    title: '破風鷹眼',
    role: 'ranger',
    baseStats: { hp: 10, attack: 1, defense: 1, speed: 1, healing: 1 },
    skillIds: ['basic_attack', 'focused_shot'],
    starterSkillIds: [
      'grass.multistrike.first_actor',
      'grass.stack.on_hit',
      'fire.chain.target_poisoned',
      'grass.weaken.on_repeat_hit',
      'water.chain.lone_target',
      'grass.blast.consume_poison',
    ],
    deliveryPassive: {
      id: 'eagle-eye-delivery',
      name: '鷹眼追獵',
      description: '萊拉每次改選目標或彈射時，追加一次獨立追擊事件。',
    },
  },
  {
    id: 'elin',
    name: '艾琳',
    title: '晨光祈禱者',
    role: 'cleric',
    baseStats: { hp: 10, attack: 1, defense: 1, speed: 1, healing: 1 },
    skillIds: ['basic_attack', 'healing_prayer'],
    starterSkillIds: [
      'water.stack.round_open',
      'water.empower.after_skill',
      'water.multistrike.consume_tide',
      'fire.empower.previous_water',
      'grass.stack.actor_strengthened',
      'water.blast.team_three_elements',
    ],
    deliveryPassive: {
      id: 'morning-tide-delivery',
      name: '晨潮祝禱',
      description: '艾琳釋放水屬技能時，同步蓄潮並治療目前生命最低的隊友。',
    },
  },
  {
    id: 'seph',
    name: '賽芙',
    title: '瘴霧鍊金師',
    role: 'alchemist',
    baseStats: { hp: 10, attack: 1, defense: 1, speed: 1, healing: 1 },
    skillIds: ['basic_attack'],
    starterSkillIds: [
      'grass.stack.battle_open',
      'grass.chain.target_burning',
      'fire.blast.target_poisoned',
      'grass.weaken.layer_threshold',
      'water.empower.consume_poison',
      'grass.multistrike.consume_mixed',
    ],
    deliveryPassive: {
      id: 'catalyst-delivery',
      name: '異相催化',
      description: '賽芙命中帶有其他屬性層的敵人時，生成一次毒霧擴散。',
    },
  },
  {
    id: 'lorne',
    name: '洛恩',
    title: '潮汐軍師',
    role: 'tactician',
    baseStats: { hp: 10, attack: 1, defense: 1, speed: 1, healing: 1 },
    skillIds: ['basic_attack'],
    starterSkillIds: [
      'water.empower.first_actor',
      'water.stack.previous_grass',
      'fire.weaken.previous_water',
      'grass.chain.ally_same_element',
      'water.multistrike.on_echo',
      'water.blast.final_actor',
    ],
    deliveryPassive: {
      id: 'tide-order-delivery',
      name: '改令成潮',
      description: '洛恩被臨時調整到下一位時，為自己與下一位角色各建立一次強化。',
    },
  },
  {
    id: 'kyro',
    name: '凱洛',
    title: '燼刃決鬥者',
    role: 'duelist',
    baseStats: { hp: 10, attack: 1, defense: 1, speed: 1, healing: 1 },
    skillIds: ['basic_attack'],
    starterSkillIds: [
      'fire.multistrike.target_burning',
      'fire.stack.on_repeat_hit',
      'grass.weaken.previous_fire',
      'water.chain.on_echo',
      'fire.blast.on_overkill',
      'fire.chain.lone_target',
    ],
    deliveryPassive: {
      id: 'ember-finale-delivery',
      name: '燼刃壓軸',
      description: '凱洛越晚出手，最後一次命中的追加事件越多。',
    },
  },
];
