import type { VisualUnitSource } from '@expedition/pixi-renderer';

export function createDemoSources(): VisualUnitSource[] {
  return [
    {
      id: 'ironwall-heavy',
      factionId: 'expedition',
      troopCount: 1_000,
      position: { x: 215, y: 210 },
      targetPosition: { x: 410, y: 225 },
      direction: { x: 1, y: 0.08 },
      formation: 'DENSE_BLOCK',
      executionState: 'MOVING',
      shape: 'SQUARE',
      color: 0x6fb6d9,
      pointScale: 0.32,
    },
    {
      id: 'pinewatch-archers',
      factionId: 'expedition',
      troopCount: 800,
      position: { x: 240, y: 430 },
      targetPosition: { x: 455, y: 395 },
      direction: { x: 0.98, y: -0.18 },
      formation: 'LINE',
      executionState: 'MOVING',
      shape: 'TRIANGLE',
      color: 0xa7d8b1,
      pointScale: 0.56,
    },
    {
      id: 'dawnlance-cavalry',
      factionId: 'expedition',
      troopCount: 600,
      position: { x: 440, y: 525 },
      targetPosition: { x: 650, y: 405 },
      direction: { x: 0.87, y: -0.5 },
      formation: 'WEDGE',
      executionState: 'MOVING',
      shape: 'DIAMOND',
      color: 0xe6c66b,
      pointScale: 0.4,
    },
    {
      id: 'greyfang-pack',
      factionId: 'greyfang',
      troopCount: 1_200,
      position: { x: 835, y: 280 },
      targetPosition: { x: 650, y: 275 },
      direction: { x: -1, y: 0 },
      formation: 'LOOSE',
      executionState: 'ROUTING',
      shape: 'CIRCLE',
      color: 0xd66d62,
      pointScale: 0.52,
    },
  ];
}
