import type { CardCatalog, ComboCardDefinition } from '@expedition/shared-types';

const CARDS: readonly ComboCardDefinition[] = [
  {
    id: 'brann_brace',
    ownerId: 'brann',
    name: '架盾',
    description: '建立格擋，讓後續反擊接上軍令。',
    cueId: 'block',
    emitsTags: ['block'],
    effects: [{ kind: 'shield', target: 'self', amount: 30 }],
  },
  {
    id: 'brann_riposte',
    ownerId: 'brann',
    name: '盾後反擊',
    description: '格擋後重擊集火目標。',
    cueId: 'hit',
    requiresTags: ['block'],
    emitsTags: ['hit'],
    effects: [{ kind: 'damage', target: 'selected_enemy', amount: 70 }],
  },
  {
    id: 'brann_shield_crash',
    ownerId: 'brann',
    name: '盾牆衝撞',
    description: '把格擋轉成另一個命中起點。',
    cueId: 'break',
    requiresTags: ['block'],
    emitsTags: ['hit', 'staggered'],
    effects: [{ kind: 'damage', target: 'selected_enemy', amount: 55 }],
  },
  {
    id: 'brann_sweep',
    ownerId: 'brann',
    name: '破陣橫掃',
    description: '命中後橫掃全體敵軍。',
    cueId: 'hit',
    requiresTags: ['hit'],
    emitsTags: ['area'],
    effects: [{ kind: 'damage', target: 'all_enemies', amount: 70 }],
  },
  {
    id: 'brann_fortress_breaker',
    ownerId: 'brann',
    name: '城塞粉碎',
    description: '格擋反擊後把整排敵人轟進崩解狀態。',
    cueId: 'break',
    requiresTags: ['block', 'hit'],
    emitsTags: ['area', 'staggered'],
    effects: [{ kind: 'damage', target: 'all_enemies', amount: 220 }],
  },
  {
    id: 'lyra_mark',
    ownerId: 'lyra',
    name: '鷹眼標記',
    description: '標記弱點，開啟精準射擊路線。',
    cueId: 'stack',
    emitsTags: ['marked'],
    effects: [],
  },
  {
    id: 'lyra_piercing_shot',
    ownerId: 'lyra',
    name: '貫心箭',
    description: '射穿已標記的集火目標。',
    cueId: 'hit',
    requiresTags: ['marked'],
    emitsTags: ['hit'],
    effects: [{ kind: 'damage', target: 'selected_enemy', amount: 90 }],
  },
  {
    id: 'lyra_quickshot',
    ownerId: 'lyra',
    name: '疾射',
    description: '不需前置條件的快速命中。',
    cueId: 'hit',
    emitsTags: ['hit'],
    effects: [{ kind: 'damage', target: 'selected_enemy', amount: 45 }],
  },
  {
    id: 'lyra_ricochet',
    ownerId: 'lyra',
    name: '彈射箭雨',
    description: '命中後在所有存活敵人間彈射。',
    cueId: 'ricochet',
    requiresTags: ['hit'],
    emitsTags: ['area', 'ricochet'],
    effects: [{ kind: 'damage', target: 'all_enemies', amount: 65 }],
  },
  {
    id: 'lyra_storm_volley',
    ownerId: 'lyra',
    name: '暴雷箭雨',
    description: '標記後傾瀉箭雨，讓整片戰場同時爆出命中。',
    cueId: 'ricochet',
    requiresTags: ['marked'],
    emitsTags: ['hit', 'area', 'ricochet'],
    effects: [{ kind: 'damage', target: 'all_enemies', amount: 95 }],
  },
  {
    id: 'lyra_killshot',
    ownerId: 'lyra',
    name: '王者斷首',
    description: '沿著標記與命中軌跡射出處決級單點終結。',
    cueId: 'boss-execution',
    requiresTags: ['marked', 'hit'],
    emitsTags: ['hit'],
    effects: [{ kind: 'damage', target: 'selected_enemy', amount: 155 }],
  },
  {
    id: 'elin_prayer',
    ownerId: 'elin',
    name: '晨光祈禱',
    description: '治療最低生命隊友，建立治療觸發。',
    cueId: 'heal',
    emitsTags: ['healed', 'heal_overflow'],
    effects: [{ kind: 'heal', target: 'lowest_hp_ally', amount: 45 }],
  },
  {
    id: 'elin_overflow_bolt',
    ownerId: 'elin',
    name: '溢光裁決',
    description: '把治療觸發轉成對敵傷害。',
    cueId: 'hit',
    requiresTags: ['healed'],
    emitsTags: ['hit'],
    effects: [{ kind: 'damage', target: 'selected_enemy', amount: 80 }],
  },
  {
    id: 'elin_aegis',
    ownerId: 'elin',
    name: '聖光庇護',
    description: '治療後展開護盾並建立格擋。',
    cueId: 'block',
    requiresTags: ['healed'],
    emitsTags: ['block'],
    effects: [{ kind: 'shield', target: 'self', amount: 30 }],
  },
  {
    id: 'elin_radiant_burst',
    ownerId: 'elin',
    name: '輝光爆裂',
    description: '命中與治療交會後引爆全場。',
    cueId: 'trigger',
    requiresTags: ['hit', 'healed'],
    emitsTags: ['area'],
    effects: [{ kind: 'damage', target: 'all_enemies', amount: 80 }],
  },
  {
    id: 'elin_judgment_hymn',
    ownerId: 'elin',
    name: '終焉聖歌',
    description: '治療完成後讓聖歌席捲全場，將續航直接轉成殲滅。',
    cueId: 'annihilation',
    requiresTags: ['healed'],
    emitsTags: ['hit', 'area', 'heal_overflow'],
    effects: [{ kind: 'damage', target: 'all_enemies', amount: 115 }],
  },
];

export const GUILD_COMBO_CARDS: CardCatalog = Object.fromEntries(
  CARDS.map((card) => [card.id, card]),
);
