import {
  MODULE_EFFECT_IDS,
  MODULE_ROLE_IDS,
  MODULE_TARGET_IDS,
  MODULE_TRIGGER_IDS,
  THREAT_KIND_IDS,
  THREAT_MODIFIER_IDS,
  WORLD_RULE_IDS,
} from '@expedition/shared-types';

const text = (maximum: number) => ({ type: 'string', minLength: 1, maxLength: maximum });

export const GAME_GENOME_JSON_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  required: [
    'version',
    'seed',
    'title',
    'premise',
    'aliases',
    'winDescription',
    'failDescription',
    'rules',
    'modules',
    'threats',
    'counters',
    'endings',
  ],
  properties: {
    version: { const: 1 },
    seed: text(80),
    title: text(80),
    premise: text(240),
    aliases: {
      type: 'object',
      required: ['PROGRESS', 'INTEGRITY', 'INSTABILITY', 'CREDITS'],
      properties: Object.fromEntries(
        ['PROGRESS', 'INTEGRITY', 'INSTABILITY', 'CREDITS'].map((id) => [id, text(16)]),
      ),
    },
    winDescription: text(160),
    failDescription: text(160),
    rules: {
      type: 'array',
      minItems: 2,
      maxItems: 2,
      uniqueItems: true,
      items: { enum: WORLD_RULE_IDS },
    },
    modules: {
      type: 'array',
      minItems: 12,
      maxItems: 12,
      items: {
        type: 'object',
        required: [
          'id',
          'name',
          'description',
          'role',
          'trigger',
          'effect',
          'target',
          'baseValue',
          'cost',
          'cooldown',
        ],
        properties: {
          id: text(40),
          name: text(32),
          description: text(160),
          role: { enum: MODULE_ROLE_IDS },
          trigger: { enum: MODULE_TRIGGER_IDS },
          effect: { enum: MODULE_EFFECT_IDS },
          target: { enum: MODULE_TARGET_IDS },
          baseValue: { type: 'integer', minimum: 0, maximum: 30 },
          cost: { type: 'integer', minimum: 1, maximum: 20 },
          cooldown: { type: 'integer', minimum: 0, maximum: 3 },
          repeatOnce: { type: 'boolean' },
        },
      },
    },
    threats: {
      type: 'array',
      minItems: 7,
      maxItems: 7,
      items: {
        type: 'object',
        required: [
          'id',
          'round',
          'name',
          'telegraph',
          'kind',
          'targetProgress',
          'integrityDamage',
          'instabilityGain',
          'modifier',
        ],
        properties: {
          id: text(40),
          round: { type: 'integer', minimum: 1, maximum: 7 },
          name: text(40),
          telegraph: text(160),
          kind: { enum: THREAT_KIND_IDS },
          targetProgress: { type: 'integer', minimum: 1, maximum: 100 },
          integrityDamage: { type: 'integer', minimum: 0, maximum: 50 },
          instabilityGain: { type: 'integer', minimum: 0, maximum: 50 },
          modifier: { enum: THREAT_MODIFIER_IDS },
          phaseTwoModifier: { enum: THREAT_MODIFIER_IDS },
        },
      },
    },
    counters: { type: 'array', minItems: 3, maxItems: 3 },
    endings: { type: 'object' },
  },
} as const;
