import type { TriggerConditionDefinition, TriggerFamily } from '@expedition/shared-types';

const trigger = (
  id: TriggerConditionDefinition['id'],
  family: TriggerFamily,
  name: string,
  description: string,
  min = 2,
  max = 6,
): TriggerConditionDefinition => ({
  id,
  family,
  name,
  description,
  additionRoll: {
    min: Math.max(1, Math.min(5, min)),
    max: Math.max(1, Math.min(5, max)),
  },
});

export const GUILD_TRIGGER_CONDITIONS: readonly TriggerConditionDefinition[] = [
  trigger('battle_open', 'timing', '開戰', '全場第一次出招時追加。', 4, 8),
  trigger('round_open', 'timing', '回合開幕', '每回合第一位角色出招時追加。', 3, 7),
  trigger('first_actor', 'timing', '先鋒', '位於當前順序第一位時追加。', 3, 7),
  trigger('final_actor', 'timing', '壓軸', '位於當前順序最後一位時追加。', 5, 10),
  trigger('after_skill', 'timing', '技能收束', '技能本體事件結束後追加。', 2, 5),
  trigger('target_burning', 'status', '追燃', '目標已有燃燒層時追加。', 3, 8),
  trigger('target_poisoned', 'status', '蝕毒', '目標已有毒素層時追加。', 3, 8),
  trigger('target_tide', 'status', '逐潮', '目標已有蓄潮層時追加。', 3, 8),
  trigger('actor_strengthened', 'status', '承接強化', '角色持有強化標記時追加。', 4, 9),
  trigger('target_weakened', 'status', '痛擊弱點', '目標已被削弱時追加。', 4, 9),
  trigger('layer_threshold', 'status', '層數臨界', '任一屬性層數達門檻時追加。', 5, 10),
  trigger('consume_burn', 'consume', '燃燒引爆', '消耗當前燃燒層，逐層追加傷害。', 1, 3),
  trigger('consume_poison', 'consume', '毒素榨取', '消耗當前毒素層，逐層追加傷害。', 1, 3),
  trigger('consume_tide', 'consume', '潮汐釋放', '消耗當前蓄潮層，逐層追加治療與傷害。', 1, 3),
  trigger('consume_all_burn', 'consume', '焚盡', '清空燃燒並為每層建立爆發事件。', 2, 4),
  trigger('consume_all_poison', 'consume', '毒霧傾瀉', '清空毒素並為每層建立擴散事件。', 2, 4),
  trigger('consume_all_tide', 'consume', '決堤', '清空蓄潮並為每層建立迴響事件。', 2, 4),
  trigger('consume_mixed', 'consume', '三相反應', '消耗兩種以上屬性層並依總層數追加。', 3, 6),
  trigger('on_hit', 'impact', '命中追擊', '每次命中後追加一個獨立事件。', 2, 5),
  trigger('on_repeat_hit', 'impact', '連打升溫', '同技能第二次起的命中逐次追加。', 2, 6),
  trigger('on_bounce', 'impact', '彈射追擊', '彈射抵達新目標或原目標迴響時追加。', 3, 7),
  trigger('on_echo', 'impact', '迴響', '單體連鎖回到原目標時追加。', 3, 7),
  trigger('on_defeat', 'impact', '擊破追獵', '敵人被擊破時立刻追加並重新選敵。', 5, 9),
  trigger('on_overkill', 'impact', '溢傷處刑', '目標倒下後仍有事件時追加溢傷。', 5, 10),
  trigger('previous_fire', 'relay', '接續火勢', '上一位角色使用火屬技能時追加。', 3, 8),
  trigger('previous_grass', 'relay', '接續草蝕', '上一位角色使用草屬技能時追加。', 3, 8),
  trigger('previous_water', 'relay', '接續水潮', '上一位角色使用水屬技能時追加。', 3, 8),
  trigger('ally_same_element', 'relay', '同調接力', '本回合已有隊友使用相同屬性時追加。', 4, 9),
  trigger('team_three_elements', 'relay', '三相輪轉', '本回合三種屬性均已出現時追加。', 6, 12),
  trigger('lone_target', 'relay', '孤王迴路', '場上只剩一名敵人時允許連鎖回到同一目標。', 4, 9),
];
