import type { UnitState, UnitType } from '@expedition/shared-types';

function createUnit(
  id: string,
  name: string,
  unitType: UnitType,
  overrides: Partial<UnitState>,
): UnitState {
  return {
    id,
    definitionId: id,
    factionId: 'expedition',
    name,
    unitType,
    classId: unitType.toLowerCase(),
    level: 1,
    experience: 0,
    troopCount: 100,
    initialTroopCount: 100,
    woundedCount: 0,
    deadCount: 0,
    routedCount: 0,
    missingCount: 0,
    capturedCount: 0,
    position: { x: 10, y: 20 },
    direction: { x: 1, y: 0 },
    morale: 1,
    moraleState: 'STEADY',
    fatigue: 0,
    cohesion: 0.9,
    discipline: 0.9,
    commandEfficiency: 0.9,
    attack: 9,
    defense: 8,
    frontalDefense: 8,
    mobility: 2,
    carryingCapacity: 10,
    equipmentWeight: 0,
    formation: 'DENSE_BLOCK',
    executionState: 'IDLE',
    equipmentLoadoutId: `starter-${id}`,
    equipmentIds: [],
    appearanceIds: [],
    skillIds: [],
    passiveIds: [],
    statusEffectIds: [],
    ...overrides,
  };
}

export function createPlayerArmy(): UnitState[] {
  return [
    createUnit('ironwall-heavy', '第一重步兵團', 'HEAVY_INFANTRY', {
      position: { x: 10, y: 18 },
      troopCount: 1_000,
      initialTroopCount: 1_000,
      attack: 10,
      defense: 11,
      frontalDefense: 11,
      mobility: 2,
      formation: 'DENSE_BLOCK',
    }),
    createUnit('pinewatch-archers', '松望弓兵團', 'ARCHER', {
      position: { x: 8, y: 38 },
      troopCount: 800,
      initialTroopCount: 800,
      attack: 12,
      defense: 6,
      frontalDefense: 6,
      mobility: 2.5,
      formation: 'LINE',
    }),
    createUnit('dawnlance-cavalry', '曙槍騎兵隊', 'CAVALRY', {
      position: { x: 14, y: 52 },
      troopCount: 600,
      initialTroopCount: 600,
      attack: 14,
      defense: 7,
      frontalDefense: 7,
      mobility: 4,
      formation: 'WEDGE',
    }),
    createUnit('ember-hero-team', '餘燼英雄小隊', 'HERO_TEAM', {
      position: { x: 6, y: 28 },
      troopCount: 120,
      initialTroopCount: 120,
      attack: 16,
      defense: 12,
      frontalDefense: 10,
      mobility: 3,
      formation: 'LOOSE',
    }),
  ];
}
